<?php

namespace AppBundle\Repository;

/**
 * RecrutementUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecrutementUserRepository extends \Doctrine\ORM\EntityRepository
{
}
